### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by MyMQL** [Ceglaa/CustomBreachScenarios#4]
This plugin dont work on the latest version of exiled

**Comment by Ceglaa** [comment]
Expect update in max 4 days, working on it

**Comment by MyMQL** [comment]
Ok, thank you

**Comment by Ceglaa** [comment]
Beta update released, check if everything works fine.
Make a backup of all existing scenarios in case of unexpected behavior of serializer, as i added a new option `TeslasDisabled`

https://github.com/Ceglaa/CustomBreachScenarios/releases/tag/1.1.0-beta.1

**Comment by MyMQL** [comment]
Ok, I will test and see if I can find any bugs.
